"""empty message

Revision ID: 826ead1fbbe4
Revises: 47d114873a4d
Create Date: 2020-12-28 00:10:11.422711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826ead1fbbe4'
down_revision = '47d114873a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('Venue', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
