"""empty message

Revision ID: af6e726c6bcd
Revises: 826ead1fbbe4
Create Date: 2020-12-28 10:24:17.255032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6e726c6bcd'
down_revision = '826ead1fbbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###
